### PR TITLE
Restaurant page

### PR DESCRIPTION
**Pull request by NiiazalyDzhumaliev**
I have created a restaurant page using only JavaScript.
- use webpack;
- use npm;

Please kindly review the project

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @NiiazalyDzhumaliev 
### The pr has a conflict, kindly fix and submit for another code review. Good luck.
conflict
- Happy coding!

**Comment by NiiazalyDzhumaliev** [comment]
I have tried to do the same

Screenshot_1

Screenshot_2

**Review by rOluochKe — CHANGES_REQUESTED** [review]
### I am sorry to tell you but I still get the same error, conflicts, can you push what you have upstream. The conflict is on readme file. Then submit for another code review. Good luck.

**Comment by NiiazalyDzhumaliev** [comment]
Edited readme file

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @NiiazalyDzhumaliev 
### You have done so far :clap: However, you have a few issues to fix:-
- [ ] Display the menu tab with food displayed in grid-like format, refer from the design
- [ ] In the scripts in package.json add this automation, see below
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
- [ ] Install all the required dependencies and run this command `npx stylelint "**/*.{css,scss}"` in case of any errors kindly fix - [follow this guide](https://github.com/microverseinc/linters-config/tree/master/javascript)
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by NiiazalyDzhumaliev** [comment]
Thanks for the reasonable comments.

- add lines to package.json;
- add grid-style menu;
- check linter

**Review by rOluochKe — APPROVED** [review]
Hello @NiiazalyDzhumaliev 
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
